export { default as WebsocketCat } from './WebsocketCat'
export { default as SmartCat } from './SmartCat'
export { default as WheelOfFortuneCat } from './WheelOfFortuneCat'
export { default as AboutMe } from './AboutMe'
export { default as AboutProject } from './AboutProject'
export { default as ContactForm } from './ContactForm'
export { default as CurvedBackground } from './CurvedBackground'
